---

podSecurityContext:
  fsGroup: null
  runAsUser: null

securityContext:
   runAsUser: null

logstashConfig:
  logstash.yml: |
    xpack:
      monitoring:
        enabled: true
        elasticsearch.hosts: http://elasticsearch-master:9200      
