---

podSecurityContext:
  fsGroup: null
  runAsUser: null

securityContext:
   runAsUser: null

logstashConfig:
  logstash.yml: |
    monitoring:
      enabled: true
      elasticsearch.hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'      
